# This workflow will install Python dependencies, generate and then publish distribution archives.
name: Deploy

on:
  workflow_run:
    branches: [ main ]
    workflows: [ "Continuous Integration" ]
    types:
      - completed

jobs:
  deploy:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.x' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
